/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkedinCallbackRouteImport } from './routes/linkedin-callback'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as PublicPublicIdRouteImport } from './routes/public/$publicId'
import { Route as AuthLinkedinIndexRouteImport } from './routes/_auth/linkedin/index'
import { Route as AuthCvIndexRouteImport } from './routes/_auth/cv/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinCallbackRoute = LinkedinCallbackRouteImport.update({
  id: '/linkedin-callback',
  path: '/linkedin-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const PublicPublicIdRoute = PublicPublicIdRouteImport.update({
  id: '/public/$publicId',
  path: '/public/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkedinIndexRoute = AuthLinkedinIndexRouteImport.update({
  id: '/linkedin/',
  path: '/linkedin/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCvIndexRoute = AuthCvIndexRouteImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/linkedin-callback': typeof LinkedinCallbackRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/public/$publicId': typeof PublicPublicIdRoute
  '/cv/': typeof AuthCvIndexRoute
  '/linkedin/': typeof AuthLinkedinIndexRoute
}
export interface FileRoutesByTo {
  '/linkedin-callback': typeof LinkedinCallbackRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/public/$publicId': typeof PublicPublicIdRoute
  '/': typeof AuthIndexRoute
  '/cv': typeof AuthCvIndexRoute
  '/linkedin': typeof AuthLinkedinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/linkedin-callback': typeof LinkedinCallbackRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/public/$publicId': typeof PublicPublicIdRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/cv/': typeof AuthCvIndexRoute
  '/_auth/linkedin/': typeof AuthLinkedinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/linkedin-callback'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/public/$publicId'
    | '/cv/'
    | '/linkedin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/linkedin-callback'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/public/$publicId'
    | '/'
    | '/cv'
    | '/linkedin'
  id:
    | '__root__'
    | '/_auth'
    | '/linkedin-callback'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/public/$publicId'
    | '/_auth/'
    | '/_auth/cv/'
    | '/_auth/linkedin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LinkedinCallbackRoute: typeof LinkedinCallbackRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  PublicPublicIdRoute: typeof PublicPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-callback': {
      id: '/linkedin-callback'
      path: '/linkedin-callback'
      fullPath: '/linkedin-callback'
      preLoaderRoute: typeof LinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/public/$publicId': {
      id: '/public/$publicId'
      path: '/public/$publicId'
      fullPath: '/public/$publicId'
      preLoaderRoute: typeof PublicPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/linkedin/': {
      id: '/_auth/linkedin/'
      path: '/linkedin'
      fullPath: '/linkedin/'
      preLoaderRoute: typeof AuthLinkedinIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cv/': {
      id: '/_auth/cv/'
      path: '/cv'
      fullPath: '/cv/'
      preLoaderRoute: typeof AuthCvIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCvIndexRoute: typeof AuthCvIndexRoute
  AuthLinkedinIndexRoute: typeof AuthLinkedinIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthCvIndexRoute: AuthCvIndexRoute,
  AuthLinkedinIndexRoute: AuthLinkedinIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LinkedinCallbackRoute: LinkedinCallbackRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  PublicPublicIdRoute: PublicPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
